apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tanzu-portal
spec:
  portal:
    password: "password"
    capacity: 5
    expires: 90m
    orphaned: 5m
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: 5
    title: Tanzu Workshop Portal
  workshops:
  - name: lab-tanzu-env-workshop
