apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tanzu-portal
spec:
  portal:
    capacity: 5
    expires: 90m
    orphaned: 5m
    password: TanzuWorkshop
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: 5
    title: Tanzu Workshop Portal
  workshops:
  - name: lab-k8s-fundamentals
  - name: lab-tanzu-env
