apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  annotations:
  name: lab-tanzu-env
spec:
  content:
    files: github.com/fcarta29/tanzu-advanced-poc
    #image: fcarta29/eduk8s-tanzu-workshop:latest
    image: harbor.tanzu.frankcarta.com/builders/eduk8s-tanzu-workshop:latest
  description: An workshop to explore Tanzu Advanced
  difficulty: intermediate
  duration: 120m
  session:
    applications:
      docker:
        enabled: true
      registry:
        enabled: true
      terminal:
        enabled: true
    namespaces:
      budget: xx-large
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
  tags:
  - containers
  title: Tanzu Globals SE Workshop
  #url: https://github.com/fcarta29/tanzu-advanced-poc
  url: https://github.com/fcarta29/tanzu-globals-se-workshop
  vendor: eduk8s.io
